### ISSUE TITLE
CSS doesn't work as expected when using `import style from './style.css'`

### ISSUE THREAD

**Issue by grazianobolla** [preactjs/preact#3446]
```js
import style from './style.css'

const Component = () => (
<div class={style.panel}>
    <p>Paragraph 1</p>
    <p id="small">Paragraph 2 Small</p>
<div>
);
```

```css
.panel {
    background: #ffffff;
}

.panel #small {
    font-size: smaller;
}
```

For some reason that doesn't work, I have to create a custom .paragraph_small class and do this instead:
```js
import style from './style.css'

const Component = () => (
<div class={style.panel}>
    <p>Paragraph 1</p>
    <p class={style.paragraph_small}>Paragraph 2 Small</p>
<div>
);
```
